# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml
# Or use the DigitalOcean dashboard to import from GitHub

name: viralclip

# GitHub repository configuration
# Uncomment and update with your repo details
# github:
#   repo: pcoll8/Vid_app
#   branch: main
#   deploy_on_push: true

services:
  - name: api
    dockerfile_path: Dockerfile
    
    # Resource sizing - adjust based on your needs
    # basic-xxs: 1 vCPU, 512MB RAM ($5/month)
    # basic-xs: 1 vCPU, 1GB RAM ($10/month)
    # basic-s: 1 vCPU, 2GB RAM ($20/month) - Recommended for video processing
    # basic-m: 2 vCPU, 4GB RAM ($40/month) - Best for production
    instance_size_slug: basic-s
    instance_count: 1
    
    # HTTP configuration
    http_port: 8080
    
    # Health check
    health_check:
      http_path: /api/settings/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
    
    # Environment variables (set in DigitalOcean dashboard or here)
    envs:
      # Required - Gemini AI
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      # Optional - AWS S3 for cloud backup
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_REGION
        scope: RUN_TIME
        value: "us-east-1"
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        value: ""
      
      # Optional - ElevenLabs for voice dubbing
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      # Optional - Instagram API
      - key: INSTAGRAM_ACCESS_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: INSTAGRAM_BUSINESS_ACCOUNT_ID
        scope: RUN_TIME
        value: ""
      
      # Optional - YouTube API
      - key: YOUTUBE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: YOUTUBE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      
      # Processing configuration
      - key: WHISPER_MODEL
        scope: RUN_TIME
        value: "base"
      - key: MIN_CLIP_DURATION
        scope: RUN_TIME
        value: "45"
      - key: MAX_CLIP_DURATION
        scope: RUN_TIME
        value: "60"
      - key: VIRAL_MOMENTS_COUNT
        scope: RUN_TIME
        value: "5"

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
